server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth_app_yt
    username: root
    password: manager
    driver-class-name: com.mysql.cj.jdbc.Driver

#    hikari:
#      pool-name: HikariCP
#      maximum-pool-size: 10
#      connection-timeout: 10000
#      idle-timeout: 600000
#      max-lifetime: 1800000
#      validation-timeout: 5000
#      leak-detection-threshold: 0
#      initialization-fail-timeout: -1

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
